### ISSUE TITLE
Error manually posting RAW events to API (Russian locale)

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#364]
Via: http://docs.getseq.net/v2/discuss/56c5727373eb9a1700fbc92d

POST body:

```json
{
"Events": [{
"Timestamp": "2015-05-09T22:09:08.12345+10:00",
"Level": "Warning",
"MessageTemplate": "Disk space is low on {Drive}",
"Properties": {
"Drive": "C:",
"MachineName": "nblumhardt-rmbp"
}
}]
}
```

Error:

```
[11:22:15 ERR] Error serving http://192.168.1.54:5341/api/events/raw (token: f6f0779c8a294d57bba0653055832155)
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Для имени "Properties" выполнена привязка к методу. Невозможно использовать его как свойство
в CallSite.Target(Closure , CallSite , Object )
в Seq.Server.Storage.StorageEventNormalizer.Normalize(Object evt, ApiKey apiKey, StorageEventCreationData& creationData, String& error)
в CallSite.Target(Closure , CallSite , Type , Object , ApiKey , StorageEventCreationData& , String& )
в Seq.Server.Web.Api.Events.RawEventsModule.CreateEventsFromRaw()
в Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b3(Object parameters, CancellationToken context)
```

The same POST body succeeds locally, suggesting:

* Locale-related issues
* Older JSON.NET version is in GAC

**Comment by nblumhardt** [comment]
The runtime binder error is reproduced with:

```
> dynamic x = DateTime.UtcNow;
> x.ToString = 5;
The name 'ToString' is bound to a method and cannot be used like a property
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Scripting.Hosting.ObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.DisplayException(Exception e)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.TryBuildAndRun(Script`1 newScript, InteractiveScriptGlobals globals, ScriptState`1& state, ScriptOptions& options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveLoop(ScriptOptions options, String initialScriptCodeOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveCore(ErrorLogger errorLogger)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractive()
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.Csi.Main(String[] args)
```

**Comment by nblumhardt** [comment]
No further reports/repro of this issue; closing until we have something to go on.
