### ISSUE TITLE
JS error in signals pane

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-releases#483]
When i open the events tab and click on a signal, **nothing** happens (signal isn't selected, events aren't filtered, etc).
Opening the console shows this error when i click on the signal name.
When i refresh the page using `CTRL + R` and click on the signal again, it works as expected.
Weirdly the error re-appears sometime later again.
```
TypeError: Unable to get property "intersected" of undefined or null reference.
   at t.toggle (http://tld:5341/seq-ui2.min.js:121:687)
   at Anonymous function (http://tld:5341/vendor.min.js:4:10898)
   at i (http://tld:5341/vendor.min.js:4:17438)
   at d.prototype.$eval (http://tld:5341/vendor.min.js:3:1544)
   at d.prototype.$apply (http://tld:5341/vendor.min.js:3:1757)
   at Anonymous function (http://tld:5341/vendor.min.js:4:17488)
   at n (http://tld:5341/vendor.min.js:1:15060)
```

This is using Seq 3.3.21 and IE11 on Windows 10 1511 and seems to be a regression over 3.2

**Comment by nblumhardt** [comment]
Thanks Robin - I haven't encountered this yet but I'll open up IE and see if I can find a way to repro it. Appreciate the info!

Regards,
Nick

**Comment by Suchiman** [comment]
I've upped the debugging in IE and found this error happening first.
Seemingly happens when i brute open seq multiple times in less than a second via scroll wheel clicking.
```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24digest
   at g (http://tld:5341/vendor.min.js:2:29739)
   at d.prototype.$apply (http://tld:5341/vendor.min.js:3:1757)
   at m (http://tld:5341/seq-ui2.min.js:47:1620)
```

**Comment by nblumhardt** [comment]
Repro'd! Thank you Robin, great find :-)

**Comment by nblumhardt** [comment]
Fixed; thanks again. New build later this week :+1:
