### ISSUE TITLE
3.3.23 / 3.4.5: Group By, Order By and Limit causes exception

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-releases#505]
```sql
select count(*) from stream where Has(Username) group by Username ORDER BY COUNT(*) DESC LIMIT 100
```
causes
```
System.ArgumentNullException: Value cannot be null.
Parameter name: valueExpression
   at Seq.Storage.Queries.Planner.OrderingInstruction..ctor(CompiledPureExpression valueExpression, Boolean isDescending)
   at Seq.Storage.Queries.Planner.QueryPlanner.<>c__DisplayClass6_0.<PlanImpl>b__5(Ordering o)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Seq.Storage.Queries.Planner.QueryPlanner.PlanImpl(Query query, FilterExpression filter, QueryPlan& plan, String[]& errors)
   at Seq.Storage.Queries.Planner.QueryPlanner.Plan(Query query, FilterExpression filter, QueryPlan& plan, String[]& errors)
   at Seq.Storage.Queries.EventStoreQueryExtensions.Query(IEventStore store, String query, DateTime rangeStartUtc, DateTime rangeEndUtc, String filter, Nullable`1 cancel)
   at Seq.Server.Web.Api.Events.DataModule.<>c__DisplayClass5_0.<Query>b__0(IComponentContext ctx, CancellationToken cancel)
   at Seq.Server.Web.Api.Events.DataModule.<>c__DisplayClass5_1.<Query>b__1(CancellationToken ct)
   at Seq.Workers.WorkerPool.<>c__DisplayClass4_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Seq.Server.Web.Api.Events.DataModule.<Query>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Server.Web.Api.Events.DataModule.<<-ctor>b__3_1>d.MoveNext()
```

**Comment by nblumhardt** [comment]
Thanks for the report, Robin. This is indeed a bug :-)

For now you can work around it by creating a column alias to order by:

```sql
select count(*) from stream as c where Has(Username) group by Username ORDER BY c DESC LIMIT 100
```
