### ISSUE TITLE
An unhandled error occurred while serving the request

### ISSUE THREAD

**Issue by nvivo** [datalust/seq-releases#542]
I just installed Seq 3.4.20 on a Windows Server 2016. Started an app, and some log events started appearing for a few minutes than it stopped.

I enabled Serilog Selflog, and this showed up:
```
2017-03-27T00:47:39.7759892Z Received failed HTTP shipping result InternalServerError: {"Error":"An unhandled error occurred while serving the request (token: 40ff9341404d4164be85c02c0d331423)."}
```

Looking at Seq logs, I got this:

```
2017-03-27 00:46:01.500 +00:00 [Information] Seq "3.4.20" 64-bit running on .NET "4.0.30319.42000" and OS "Microsoft Windows NT 6.3.9600.0" 64-bit
2017-03-27 00:46:01.870 +00:00 [Information] Seq listening on [http://localhost:5341/]
2017-03-27 00:46:01.885 +00:00 [Information] This system will use ESENT sparse file support
2017-03-27 00:46:01.901 +00:00 [Information] Opening document store "D:\SeqData\Documents\default.quince"
2017-03-27 00:46:02.059 +00:00 [Information] Opening event store at "D:\SeqData\Extents"
2017-03-27 00:46:02.231 +00:00 [Information] Storage subsystem available
2017-03-27 00:46:02.314 +00:00 [Information] Cache warm-up is required
2017-03-27 00:46:02.399 +00:00 [Information] Initial memory cache warm-up "completed" in 84.7 ms
2017-03-27 00:46:04.967 +00:00 [Information] 56 segments warmed up (deduplication buffer: SharedAssets { Strings: 156, Schemata: 11, Filter: 1.28030776977539E-05 })
2017-03-27 00:47:39.785 +00:00 [Error] Error serving "http://seqserver:5341/api/events/raw" (token: "40ff9341404d4164be85c02c0d331423")
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Seq.Server.Storage.StorageEventNormalizer.<>c.<FromRawFormat>b__3_1(JProperty rp)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Seq.Server.Storage.StorageEventNormalizer.FromRawFormat(Object evt, ApiKey apiKey, StorageEventCreationData& creationData, String& error)
   at CallSite.Target(Closure , CallSite , Type , Object , ApiKey , StorageEventCreationData& , String& )
   at Seq.Server.Web.Api.Events.RawEventsModule.TryParseRawFormatBody(ApiKey apiKey, StorageEventCreationData[]& events, String& errorMessage)
   at Seq.Server.Web.Api.Events.RawEventsModule.Ingest()
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

Just for the sake of it, I tried manually deleting  all events and still nothing. Then I decided to clear the seq folder and build a new one. I restarted app and the same error:

```
2017-03-27 01:02:08.914 +00:00 [Information] Seq "3.4.20" 64-bit running on .NET "4.0.30319.42000" and OS "Microsoft Windows NT 6.3.9600.0" 64-bit
2017-03-27 01:02:09.316 +00:00 [Information] Seq listening on [http://localhost:5341/]
2017-03-27 01:02:09.332 +00:00 [Information] This system will use ESENT sparse file support
2017-03-27 01:02:09.350 +00:00 [Information] Opening document store "D:\SeqData\Documents\default.quince"
2017-03-27 01:02:09.457 +00:00 [Information] Creating new data file at "D:\SeqData\Documents\default.quince"
2017-03-27 01:02:09.573 +00:00 [Information] Creating "SchemaVersions" table
2017-03-27 01:02:09.618 +00:00 [Information] Applying migration "Create the document store"
2017-03-27 01:02:09.643 +00:00 [Information] Applying migration "Check for App instances without Apps"
2017-03-27 01:02:09.654 +00:00 [Information] Applying migration "Create the server license"
2017-03-27 01:02:09.700 +00:00 [Information] Applying migration "Create the Administrator account"
2017-03-27 01:02:09.716 +00:00 [Information] Applying migration "Install the watches app"
2017-03-27 01:02:09.733 +00:00 [Information] Applying migration "Update permissions for the Administrator account"
2017-03-27 01:02:09.745 +00:00 [Information] Applying migration "Configure the public NuGet feed"
2017-03-27 01:02:09.755 +00:00 [Information] Applying migration "Store the default system configuration"
2017-03-27 01:02:09.759 +00:00 [Information] Applying migration "Ensure the license supports this version - 3.4.20.0"
2017-03-27 01:02:09.762 +00:00 [Information] Applying migration "Ensure the default system configuration has an id"
2017-03-27 01:02:09.764 +00:00 [Information] Applying migration "Use direct (unbuffered) input to trigger watches"
2017-03-27 01:02:09.766 +00:00 [Information] Applying migration "Apply master key to app settings"
2017-03-27 01:02:09.767 +00:00 [Information] Applying migration "Re-encrypt NuGet feed passwords with portable key"
2017-03-27 01:02:09.771 +00:00 [Information] Applying migration "Use direct (unbuffered) input to trigger watches - reapply"
2017-03-27 01:02:09.773 +00:00 [Information] Applying migration "Configure default SQL queries"
2017-03-27 01:02:09.777 +00:00 [Information] Applying migration "Make default queries visible to all users"
2017-03-27 01:02:09.807 +00:00 [Information] Applying migration "Configure default signals"
2017-03-27 01:02:09.826 +00:00 [Information] Applying migration "Make default signals visible to all users"
2017-03-27 01:02:09.838 +00:00 [Information] Applying migration "Map user accounts to the default AD domain, if one is configured"
2017-03-27 01:02:09.874 +00:00 [Information] Opening event store at "D:\SeqData\Extents"
2017-03-27 01:02:09.915 +00:00 [Information] Storage subsystem available
2017-03-27 01:02:45.739 +00:00 [Error] Error serving "http://seqserver:5341/api/events/raw" (token: "6dbc669e5a6242fab8bc0d0c081f68ee")
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Seq.Server.Storage.StorageEventNormalizer.<>c.<FromRawFormat>b__3_1(JProperty rp)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Seq.Server.Storage.StorageEventNormalizer.FromRawFormat(Object evt, ApiKey apiKey, StorageEventCreationData& creationData, String& error)
   at CallSite.Target(Closure , CallSite , Type , Object , ApiKey , StorageEventCreationData& , String& )
   at Seq.Server.Web.Api.Events.RawEventsModule.TryParseRawFormatBody(ApiKey apiKey, StorageEventCreationData[]& events, String& errorMessage)
   at Seq.Server.Web.Api.Events.RawEventsModule.Ingest()
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

This is my config:
```cs
logConfig.WriteTo.Seq("http://seqserver:5341", compact: true, bufferBaseFilename: bufferBaseName);
```

The entire buffer file is 2.4mb now, the next line after the bookmark is the longest one in the file, but still it has only 31308 bytes. I thought about messing with the limits in the config, but everything seem to be under the limits of 256k per event and 10mb per batch.

I'm lost. What could be going on?

**Comment by nblumhardt** [comment]
Thanks for the report! It looks like you have hit a bug; the problem is triggered by an event with the same property, formatted with the same format, in a single log event:

```csharp
Log.Information("{A:000} and {A:000}", 42.42)
```

Here, `A` not only appears twice, but has the same custom format in both cases. The log event is technically malformed (same property captured more than once) but Serilog accepts it and will send the payload to Seq, which fails to ingest it.

Can you identify an event like this in your app? It'd be great to confirm that it's indeed the problem.

I will have a look and see what workarounds I can figure out. Thanks!

**Comment by nvivo** [comment]
You nailed it. It wasn't clear at first, but that was the problem. The issue was that at one point I was concatenating strings instead of using the template format:

```cs
log.Warning($"Server Response Error: {responseContent}");
```

The variable was an HTML page for an HTTP 500, and had CSS and JS, and turns out it's not a good idea to parse an HTML page as a template =), CSS styles look like properties. Now, looking at the line that caused the error, I see this:

![image](https://cloud.githubusercontent.com/assets/202449/24351560/8fbccd74-12bc-11e7-924c-ae28e2736510.png)

The page had a CSS block like this:

```css
... ul{display:none}.someclass{display:none}div#a{display:none} ...
```

Leaving aside my stupidity on concatenating the template, it looks like the log server not processing any messages due to one malformed message is not a good idea. But at the same time, Serilog throwing an exception during log isn't either.

It would be better to see a warning on seq or a placeholder saying "malformed message", and a property with the original unparsed content, so we can fix it.

**Comment by nblumhardt** [comment]
Great! Thanks for tracking this down, and for the thoughts.

Usually, Seq would handle these more gracefully, and show the error in the _ingestion log_. The failure to ingest this one is a bug - in 4.0 we'll just de-duplicate the values and turn this into a usable event.
