### ISSUE TITLE
TooManySortsException from Microsoft.Isam.Esent.Interop.Api.GetColumnDictionary() at startup

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#550]
On one particular machine, we've had the following issue reported when loading Seq's metadata (document) store:

```
Microsoft.Isam.Esent.Interop.EsentTooManySortsException: Too many sort processes
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err)
   at Microsoft.Isam.Esent.Interop.Api.JetGetTableColumnInfo(JET_SESID sesid, JET_TABLEID tableid, String columnName, JET_COLUMNLIST& columnlist)
   at Microsoft.Isam.Esent.Interop.Api.GetColumnDictionary(JET_SESID sesid, JET_TABLEID tableid)
```

The error appears even after a completely new database is created, suggesting that there's some machine-specific issue going on.

As mentioned in #549, we're planning to update the _Esent.Interop.dll_ dependency to take advantage of a number of bug fixes in the latest version. We've provided the customer experiencing this with an updated Seq build and will hopefully be able to confirm soon whether the issue is indeed version-specific.

**Comment by nblumhardt** [comment]
Updating _Esent.Interop.dll_ does appear to have fixed this so far (if we hear otherwise I'll re-open).

**Comment by nblumhardt** [comment]
We've seen this in the wild in version 4.1.17, reopening so that our findings can be recorded here.

**Comment by nblumhardt** [comment]
Possibly more-specific information about the error, from https://msdn.microsoft.com/en-us/library/gg269211(v=exchg.10).aspx:

JET_errTooManySorts | The operation failed because the engine cannot allocate the resources required to create a temporary table. Temporary table resources are configured using JetSetSystemParameter with JET_paramMaxTemporaryTables.
-- | --

**Comment by nblumhardt** [comment]
Settting `JET_paramMaxTemporaryTables` appears to have addressed this; will reopen if any further issues are reported.
