### ISSUE TITLE
3.x dash -> 4.x dashboard upgrade fails when an original chart has no title

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#601]
Migration fails with:

```
System.ArgumentException: A title is required.
   at Seq.Server.Data.Documents.Monitoring.Chart..ctor(String id, String title)
   at Seq.Server.Data.Documents.Monitoring.Migrations.WatchesToDashboards.Apply(QuinceSession session)
   at Quince.Migration.Migrator.Apply(QuinceSession session, String migrationName, Boolean transactional, IMigration migration, Table schemaVersions, JET_COLUMNID migrationNameColumn, JET_COLUMNID appliedAtColumn, ILogger log)
   at Quince.Migration.Migrator.Migrate(QuinceDB db, IEnumerable`1 migrations, ILogger migrationLog)
```

**Comment by nblumhardt** [comment]
Further analysis reveals that original "dash" charts only required non-null titles, while "dashboard" charts require not-null-or-whitespace titles.

**Comment by nblumhardt** [comment]
Charts with whitespace titles will now be upgraded as "(No title)"

![image](https://user-images.githubusercontent.com/342712/28344493-0c657cbe-6c67-11e7-85fd-5e49720e6300.png)
